### ISSUE TITLE
Adding papers to the list

### ISSUE THREAD

**Issue by james-york** [captn3m0/boardgame-research#2]
Hi! 
I'm a bit of newb when it comes to GitHub. I co-edit a journal on the intersection of games and play in language and literacy teaching. [LLP Journal](https://www.llpjournal.org)

We have papers on the use of board games in general, but regarding a specific game, there is a peer-reviewed paper on the use of Jenga for teaching English: https://www.llpjournal.org/2020/04/13/jidokan-jenga.html 

I wonder if it is acceptable for the list. If so, please let me know how to add it.

Thanks

James

**Comment by captn3m0** [comment]
Thanks, added these to the list.
