### ISSUE TITLE
Interested in collecting datasets/resources for board game research as well? 

### ISSUE THREAD

**Issue by JayWalker512** [captn3m0/boardgame-research#3]
I ask because I recently released a large data set of random games for the board game Shobu (you can find it here: https://www.kaggle.com/bsfoltz/shobu-randomly-played-games-104k) as well as an AI framework/game simulator for doing research in the game (here: https://github.com/JayWalker512/Shobu).

I'm not actively doing much research on this game (or any others) right now but they might be valuable resources for other folks who want to pursue this game (which it doesn't look like anyone has yet based on your list). 
 
I'm sure there are lots of datasets/tools for other games that could be aggregated as well.

**Comment by captn3m0** [comment]
Definitely yes. Feel free to file a PR with a "Shobu" category, or I'll add it soon.

If you come across any other game datasets, do post here.

**Comment by JayWalker512** [comment]
Great, I'll make a PR when I get some time.
