### ISSUE TITLE
[Submission/URL]: K-level Reasoning for Zero-Shot (Human-AI) Coordination in Hanabi

### ISSUE THREAD

**Issue by VitamintK** [captn3m0/boardgame-research#9]
### URL

https://proceedings.neurips.cc/paper/2021/file/4547dff5fd7604f18c8ee32cf3da41d7-Paper.pdf

### Game

Hanabi

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by captn3m0** [comment]
Thanks a lot 👍🏽
